### ISSUE TITLE
[Bug]: batch_config is required and cannot be set to required=False

### ISSUE THREAD

**Issue by BuzzCutNorman** [meltano/sdk#1095]
### Singer SDK Version

0.12.0

### Python Version

3.9

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Windows

### Description

I have two taps that when I add the `batch_config` to the `config_jasonschema` and run them without a `batch_config` in the meltano.yml file I get the following error 
```
singer_sdk.exceptions.ConfigValidationError: Config validation failed: 'batch_config' is a required property
```
If I try to add `required=False` to the `batch_config` top object I get this error 
```
TypeError: __init__() got multiple values for argument 'required'
```

If I remove the `batch_config` from the `config_jsonschema` it runs without error when no `batch_config` is in the `meltano.yml`. 
I can set the `batch_config` in the `meltano.yml` and it works as expected.  I am fine running without the `batch_config` in the `config_jsonschema` but wanted to see if this was a bug or me misunderstanding how deal with the `batch_config`

### Code

```python
th.Property(
            "batch_config",
            th.ObjectType(
                th.Property( 
                    "encoding",
                    th.ObjectType(
                        th.Property(
                            "format",
                            th.StringType,
                            description="Currently the only format is jsonl",
                        ),
                        th.Property(
                            "compression",
                            th.StringType,
                            description="Currently the only compression options is gzip",
                        )
                    )
                )
            ),
            th.Property(
                "storage",
                th.ObjectType(
                    th.Property(
                        "root",
                        th.StringType,
                        description="the directory you want batch messages to be placed in\n"\
                                    "example: file://test/batches",
                    ),
                    th.Property(
                        "prefix",
                        th.StringType,
                        description="What prefix you want your messages to have\n"\
                                    "example: test-batch-",
                    )
                )
            ),
            required=False,
            description="Optional Batch Message configuration",
        )


Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\Scripts\tap-sqlbuzz.exe\__main__.py", line 7, in <module>
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\singer_sdk\tap_base.py", line 489, in cli
    tap = cls(  # type: ignore  # Ignore 'type not callable'
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\singer_sdk\tap_base.py", line 540, in __init__
    super().__init__(
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\singer_sdk\tap_base.py", line 68, in __init__
    super().__init__(
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\singer_sdk\plugin_base.py", line 120, in __init__
    self._validate_config(raise_errors=validate_config)
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\lib\site-packages\singer_sdk\plugin_base.py", line 253, in _validate_config
    raise ConfigValidationError(summary)
singer_sdk.exceptions.ConfigValidationError: Config validation failed: 'batch_config' is a required property
JSONSchema was: {'type': 'object', 'properties': {'dialect': {'type': ['string', 'null'], 'description': 'The Dialect of SQLAlchamey'}, 'driver_type': {'type': ['string', 'null'], 'description': 'The Python Driver you will be using to connect to the SQL server'}, 'host': {'type': ['string', 'null'], 'description': 'The FQDN of the Host serving out the SQL Instance'}, 'port': {'type': ['integer', 'null'], 'description': 'The port on which SQL awaiting connection'}, 'user': {'type': ['string', 'null'], 'description': 'The User Account who has been granted access to the SQL Server'}, 'password': {'type': ['string', 'null'], 'description': 'The Password for the User account'}, 'database': {'type': ['string', 'null'], 'description': 'The Default database for this connection'}, 'sqlalchemy_url_query': {'type': ['object', 'null'], 'properties': {'driver': {'type': ['string', 'null'], 'description': 'The Driver to use when connection should match the Driver Type'}, 'TrustServerCertificate': {'type': ['string', 'null'], 'description': 'This is a Yes No option'}}}, 'batch_config': {'type': 'object', 'properties': {'encoding': {'type': ['object', 'null'], 'properties': {'format': {'type': ['string', 'null'], 'description': 'Currently the only format is jsonl'}, 'compression': {'type': ['string', 'null'], 'description': 'Currently the only compression options is gzip'}}}}, 'description': 'Optional Batch Message configuration'}, 'stream_maps': {'type': ['object', 'null'], 'properties': {}, 'description': 'Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).'}, 'stream_map_config': {'type': ['object', 'null'], 'properties': {}, 'description': 'User-defined config values to be used within map expressions.'}, 'flattening_enabled': {'type': ['boolean', 'null'], 'description': "'True' to enable schema flattening and automatically expand nested properties."}, 'flattening_max_depth': {'type': ['integer', 'null'], 'description': 'The max depth to flatten schemas.'}}, 'required': ['batch_config']}


PS C:\development\buzzcutnorman\tap-sqlbuzz> meltano invoke tap-sqlbuzz
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Catalog discovery failed: command ['C:\\development\\buzzcutnorman\\tap-sqlbuzz\\.meltano\\extractors\\tap-sqlbuzz\\venv\\Scripts\\tap-sqlbuzz', '--config', 'C:\\development\\buzzcutnorman\\tap-sqlbuzz\\.meltano\\run\\tap-sqlbuzz\\tap.75b00591-3f5a-4a46-b0c1-084c1560588b.config.json', '--discover'] returned 1 with stderr:
 Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\development\buzzcutnorman\tap-sqlbuzz\.meltano\extractors\tap-sqlbuzz\venv\Scripts\tap-sqlbuzz.exe\__main__.py", line 4, in <module>
  File "C:\development\buzzcutnorman\tap-sqlbuzz\tap_sqlbuzz\tap.py", line 8, in <module>
    class Tapsqlbuzz(SQLTap):
  File "C:\development\buzzcutnorman\tap-sqlbuzz\tap_sqlbuzz\tap.py", line 66, in Tapsqlbuzz
    th.Property(
TypeError: __init__() got multiple values for argument 'required'
```

**Comment by edgarrmondragon** [comment]
@BuzzCutNorman I think the arguments are passed at the wrong level?

```python
th.Property(
  "batch_config",
  th.ObjectType(
    th.Property(
      "encoding",
      th.ObjectType(
        ...
      )
    )
  ),
  th.Property(  # third positional argument to th.Property?
    "storage",
    ...
  ),
  required=False,
  description="Optional Batch Message configuration",
)
```

You want

```python
th.Property(
  "batch_config",
  th.ObjectType(
    th.Property(
      "encoding",
      th.ObjectType(
        ...
      )
    ),
    th.Property(  # third positional argument to th.Property?
      "storage",
      ...
    ),
  ),
  required=False,
  description="Optional Batch Message configuration",
)
```

**Comment by BuzzCutNorman** [comment]
@edgarrmondragon Thank you!!! for finding that for me.
