### ISSUE TITLE
bug: poetry lock contains packaging module - pyproject.toml does not

### ISSUE THREAD

**Issue by mjsqu** [meltano/sdk#1822]
https://github.com/meltano/sdk/blame/ba8c43c40957a599374ad32697a391b171610e04/singer_sdk/plugin_base.py#L15

**Comment by mjsqu** [comment]
A colleague has just been using the latest version of the SDK and installing from the `pyproject.toml` and then running with `meltano` fails with `packaging` not found.

**Comment by s7clarke10** [comment]
Here is a bit more detail around the issue running with the latest SDK.

```shell
meltano --log-level=debug invoke tap-rest-api-msdk--MDR --discover
Traceback (most recent call last):
  File "/home/my_user/meltano-projects/salesforce_pot/.meltano/extractors/tap-rest-api-msdk/venv/bin/tap-rest-api-msdk", line 5, in <module>
    from tap_rest_api_msdk.tap import TapRestApiMsdk
  File "/home/my_user/meltano-projects/salesforce_pot/.meltano/extractors/tap-rest-api-msdk/venv/lib64/python3.8/site-packages/tap_rest_api_msdk/tap.py", line 9, in <module>
    from singer_sdk import Tap
  File "/home/my_user/meltano-projects/salesforce_pot/.meltano/extractors/tap-rest-api-msdk/venv/lib64/python3.8/site-packages/singer_sdk/__init__.py", line 7, in <module>
    from singer_sdk.mapper_base import InlineMapper
  File "/home/my_user/meltano-projects/salesforce_pot/.meltano/extractors/tap-rest-api-msdk/venv/lib64/python3.8/site-packages/singer_sdk/mapper_base.py", line 14, in <module>
    from singer_sdk.plugin_base import PluginBase
  File "/home/my_user/meltano-projects/salesforce_pot/.meltano/extractors/tap-rest-api-msdk/venv/lib64/python3.8/site-packages/singer_sdk/plugin_base.py", line 15, in <module>
    from packaging.specifiers import SpecifierSet
ModuleNotFoundError: No module named 'packaging'
```

I believe package was just added two day ago here:  https://github.com/meltano/sdk/blob/ba8c43c40957a599374ad32697a391b171610e04/singer_sdk/plugin_base.py#L15 but has not been added to the pyproject.toml file so Meltano is failing because package is not available in my venv.

**Comment by edgarrmondragon** [comment]
Thanks for reporting! This merits a patch release right after we fix it.
