### ISSUE TITLE
bug: Version `0.35.0` introduces Pytest plugin error: `Plugin already registered under a different name`

### ISSUE THREAD

**Issue by anden-akkio** [meltano/sdk#2228]
### Singer SDK Version

0.35.0

### Is this a regression?

- [X] Yes

### Python Version

3.10

### Bug scope

Taps (catalog, state, etc.)

### Operating System

MacOS

### Description

Using the Pytest plugin works on `~0.34.0` but throws the below error on `~0.35.0`. 

Command run is simply `pytest`.

My test configuration is not particularly complex:

**tests/conftest.py**

```py
pytest_plugins = ("singer_sdk.testing.pytest_plugin",)
```

**tests/test_core.py**

```py
"""Tests standard tap features using the built-in SDK tests library."""
import json

from singer_sdk.testing import SuiteConfig, get_tap_test_class
from tap_hubspot.tap import TapHubspot

SAMPLE_CONFIG = json.load(open(".secrets/config.json"))

TestTapHubspot = get_tap_test_class(
    tap_class=TapHubspot,
    config=SAMPLE_CONFIG,
    suite_config=SuiteConfig(
        max_records_limit=10,
        ignore_no_records_for_streams=[
            "calls",
            "communications",
            "emails",
            "meetings",
            "notes",
            "postal_mail",
        ]
    ),
)
```

**pyproject.toml** (the relevant bits)

```toml
[tool.poetry.dependencies]
python = ">=3.10,<3.11"
requests = "^2.31.0"
singer-sdk = "~0.35.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
coverage = "^7.4.1"
mypy = "^1.8.0"
ruff = "^0.2.1"
types-requests = "^2.31.0.6"
types-pytz = "^2024.1.0.20240203"

[build-system]
requires = ["poetry-core==1.5.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tap-hubspot = 'tap_hubspot.tap:TapHubspot.cli'
```

### Code

```Python
Traceback (most recent call last):
  File "/Users/andenacitelli/tap-hubspot/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 197, in console_main
    code = main()
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 155, in main
    config = _prepareconfig(args, plugins)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 337, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/helpconfig.py", line 104, in pytest_cmdline_parse
    config = yield
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1094, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1446, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1346, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/warnings.py", line 148, in pytest_load_initial_conftests
    return (yield)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/capture.py", line 151, in pytest_load_initial_conftests
    yield
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1172, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 575, in _set_initial_conftests
    self._try_load_conftest(anchor, importmode, rootpath)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 597, in _try_load_conftest
    self._loadconftestmodules(x, importmode, rootpath)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 620, in _loadconftestmodules
    mod = self._importconftest(conftestpath, importmode, rootpath)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 675, in _importconftest
    self.consider_conftest(mod, registration_name=conftestpath_plugin_name)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 759, in consider_conftest
    self.register(conftestmodule, name=registration_name)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 510, in register
    self.consider_module(plugin)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 767, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 774, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 811, in import_plugin
    self.register(mod, modname)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 499, in register
    plugin_name = super().register(plugin, name)
  File "/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 145, in register
    raise ValueError(
ValueError: Plugin already registered under a different name: singer_sdk.testing.pytest_plugin=<module 'singer_sdk.testing.pytest_plugin' from '/Users/andenacitelli/tap-hubspot/venv/lib/python3.10/site-packages/singer_sdk/testing/pytest_plugin.py'>
```

**Comment by edgarrmondragon** [comment]
@anden-akkio thanks for logging!

You may need to remove `pytest_plugins = ("singer_sdk.testing.pytest_plugin",)` from your `tests/conftest.py`.

It's highlighted in [the release notes](https://github.com/meltano/sdk/releases/tag/v0.35.0), but perhaps we need to add a note in the testing docs?

Still, this issue helps with visibility so let me know if that fixes the problem for you!

**Comment by anden-akkio** [comment]
Makes sense. I suppose you guys are pre-1.0 so the usual semver conventions are off the table and we might want to get in the habit of pinning to a minor version -- just caught me off guard. Appreciate the followup! More docs couldn't hurt, as I can't imagine I'll be the first to run into this.

**Comment by edgarrmondragon** [comment]
> Makes sense. I suppose you guys are pre-1.0 so the usual semver conventions are off the table

That's right! I have _opinions_ about semver 😅, but yeah I figured this was an acceptable breaking change since it doesn't affect the operation of a tap, only its testing. So it would presumably be caught in CI and not in production.

> and we might want to get in the habit of pinning to a minor version

That's reasonable and the actual undocumented approach we use for our cookiecutters: https://github.com/meltano/sdk/blob/7c77366e30efff5bc04cce709ecac359fdfabc2f/cookiecutter/tap-template/%7B%7Bcookiecutter.tap_id%7D%7D/pyproject.toml#L42

> More docs couldn't hurt, as I can't imagine I'll be the first to run into this.

Right and some people even encountered it before the actual release :rofl:: https://meltano.slack.com/archives/C069RH0F95F/p1706921803307239

> A more useful message in the SDK itself (some kind of warn) would probably help too.

Yeah, maybe there's something we can do with pytest hooks.

Thanks!
