### ISSUE TITLE
ModuleNotFoundError: No module named 'jaraco'

### ISSUE THREAD

**Issue by jlloyd-widen** [meltano/sdk#2659]
### Singer SDK Version

Various: 0.36.0, 0.40.0, etc.

### Is this a regression?

- [X] Yes

### Python Version

3.11

### Bug scope

Taps (catalog, state, etc.)

### Operating System

Linux

### Description

All of my taps got reinstalled yesterday, effectively a completely clean install. All of my `singer_sdk` based taps errored out with the following error:
```
Traceback (most recent call last):
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/bin/tap-clari", line 5, in <module>
    from tap_clari.tap import TapClari
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/lib/python3.11/site-packages/tap_clari/tap.py", line 5, in <module>
    from singer_sdk import Tap
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/lib/python3.11/site-packages/singer_sdk/__init__.py", line 5, in <module>
    from singer_sdk import streams
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/lib/python3.11/site-packages/singer_sdk/streams/__init__.py", line 5, in <module>
    from singer_sdk.streams.core import Stream
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/lib/python3.11/site-packages/singer_sdk/streams/core.py", line 26, in <module>
    from singer_sdk.helpers._batch import (
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/lib/python3.11/site-packages/singer_sdk/helpers/_batch.py", line 12, in <module>
    import fs
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/lib/python3.11/site-packages/fs/__init__.py", line 4, in <module>
    __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dagster/app/meltano/.meltano/extractors/tap-clari/venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 95, in <module>
    from jaraco.text import drop_comment, join_continuation, yield_lines
ModuleNotFoundError: No module named 'jaraco'
```
That's about 8 taps, most of which I did not touch, that all went haywire on the same day, same time/build.

**Comment by edgarrmondragon** [comment]
Thanks for reporting!

I suspect this is caused by setuptools. Let me investigate.

**Comment by jlloyd-widen** [comment]
@edgarrmondragon Good find on that other example. I was looking for something like that but couldn't find it. I tried that last few major versions of `setuptools`, 70.3.0 is the last working version for me.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon Good find on that other example. I was looking for something like that but couldn't find it. I tried that last few major versions of `setuptools`, `70.3.0` is the last working version for me.

@jlloyd-widen Thanks for confirming. I think I'll add a constraint for setuptools then. We'll hopefully be able to remove `fs` as a dependency soon enough too.
