### ISSUE TITLE
feat: Schema Only Flag

### ISSUE THREAD

**Issue by joshua-janicas** [meltano/sdk#2810]
### Feature scope

Taps (catalog, state, tests, etc.)

### Description

# Feature Idea
* A configurable option or command of a tap that would perform a schema/header extract only with no data attached. This would not update any state files.
* Should be flexible with most taps (including those that are not database focused) where we just pull the "fields/column names" from our data sources and ignore the data itself.
* Example:  pg_dump with --schema-only in PostGres, BACPAC vs DACPAC in MSSQL.
* --schema-only or some more appropriate generic naming

# Use Case
- Populating a target with empty fields
- Creating a "EMPTY_DB" in Snowflake with only empty tables, no data

```
it's a weird intersection of our business intelligence software and how our upstream data is handled. we need to template reports with no data to give to our clients to publish. the rub is that each client is on a different version of our database which we import data from using tap-mssql and those versions may have schema differences. we can pin a client to a specific version of our elt pipeline but that results in potentially different tables (a column added, renamed...) (edited) 
```

**Comment by visch** [comment]
I wonder if a mapper would do this today with filters. Try setting the filter to True https://sdk.meltano.com/en/v0.43.1/stream_maps.html#filtering-out-records-from-a-stream-using-filter-operation 

Might work 🤷

**Comment by visch** [comment]
I wonder if a mapper would do this today with filters. Try setting the filter to False for every record https://sdk.meltano.com/en/v0.43.1/stream_maps.html#filtering-out-records-from-a-stream-using-filter-operation 

Might work 🤷

**Comment by visch** [comment]
If I really needed this, I'd mess with the CLI test options and manually do it so something like

1. `meltano invoke tap-name --test SCHEMA > out` 
2. `cat out | meltano invoke target-name`

**Comment by joshua-janicas** [comment]
So I've finally gotten around to trying this out. I was trying to use a tap `tap-mssql-static` that inherits from `tap-mssql`.

```
plugins:
  extractors:
  - name: tap-mssql
    variant: buzzcutnorman
    pip_url: git+https://github.com/BuzzCutNorman/tap-mssql.git@v0.1.0
    config:
      dialect: mssql
      driver_type: pyodbc
      sqlalchemy_eng_params:
        fast_executemany: 'True'
      sqlalchemy_url_query:
        driver: ODBC Driver 18 for SQL Server
```

```
plugins:
  extractors:
  - name: tap-mssql-static
    inherit_from: tap-mssql
    select:
    - Static-Country.*
    - Static-Region.*
```

A few things: 
1) Running `meltano invoke tap-name --test schema  > out` ignores the specific tap I'm trying to use and selects all the tables from the database that exist.
2) Then running `cat out | meltano invoke target-snowflake` breaks on tables in Snowflake that does not exist to begin with (particularly because of (1) listing all the tables instead of the one I want).

Stack trace is below, note that the first Admin-AdminCart already exists as a table (from another tap), but because Admin-AdminCartEtag does not exist it blows up. In reality I was hoping neither would show up, the tables that it should be trying to do is Static-Country and Static-Region. 

Even if it did that though, if those two tables didn't exist it'd be crashing out anyways. Thoughts?

<details>
<summary> Stack Trace </summary>
```
Environment 'dev' is active   
Initializing 'target-snowflake' target sink...
Initializing target sink for stream 'Admin-AdminCart'...
Private key is in PEM format
Initializing 'target-snowflake' target sink...
Initializing target sink for stream 'Admin-AdminCartEtag'...
Error creating "TEST"."RAW"."ADMINCARTETAG" {'properties': {}, 'type': 'object', 'required': ['AdminCartId']}
Traceback (most recent call last):
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\cursor.py", line 1134, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\errors.py", line 279, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\errors.py", line 334, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\errors.py", line 210, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 2 at position 0 unexpected ')'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\target_snowflake\sinks.py", line 81, in setup
    self.connector.prepare_table(
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\singer_sdk\connectors\sql.py", line 1388, in prepare_table
    self.create_empty_table(
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\singer_sdk\connectors\sql.py", line 1331, in create_empty_table
    meta.create_all(self._engine)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5925, in create_all
    bind._run_ddl_visitor(
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3249, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2456, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\sql\visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 981, in visit_metadata
    self.traverse_single(
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\sql\visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 1019, in visit_table
    )._invoke_with(self.connection)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 321, in _invoke_with
    return bind.execute(self)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 187, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1527, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\cursor.py", line 1134, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\errors.py", line 279, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\errors.py", line 334, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Git\elt-pipeline\.meltano\loaders\target-snowflake\venv\Lib\site-packages\snowflake\connector\errors.py", line 210, in default_errorhandler
    raise error_class(
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001003 (42000): SQL compilation error:
syntax error line 2 at position 0 unexpected ')'.
[SQL:
CREATE TABLE "RAW"."ADMINCARTETAG" (
)

]
```
</details>

**Comment by joshua-janicas** [comment]
I am trying visch's first idea with the mappers and that is more what I am looking for I think.

```
plugins:
  loaders:
  - name: target-snowflake-overwrite
    inherit_from: target-snowflake
    config:
      load_method: overwrite
```

```
plugins:
  extractors:
  - name: tap-mssql-static
    inherit_from: tap-mssql
    select:
    - Static-Country.*
    - Static-Region.*
  - name: tap-mssql-static-empty
    inherit_from: tap-mssql-static
    config:
      stream_maps:
        Static-Country:
          __filter__:  'False'
        Static-Region:
          __filter__: 'False'
```

Running `meltano run tap-mssql-static-empty target-snowflake-overwrite` behaves as I expect it to, I think.

Separate issue is I was trying to use the "*" https://sdk.meltano.com/en/v0.43.1/stream_maps.html#applying-a-mapping-across-two-or-more-streams but it dies because it's trying to apply the filter to all the tables it finds instead of the one's I'm trying to filter on via the inherited select.
```
      stream_maps:
        "*":
          __filter__: 'False'
```
